--wisudo: false
os: linux
dist: trusty
sudo: required
compiler: gcc
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - name: "pst tests"
      env: TEST_SCRIPT="pst_tests.py"
    - name: "utils tests"
      env: TEST_SCRIPT="utils_tests.py"
    - name: "mat tests"
      env: TEST_SCRIPT="mat_tests.py"
    - name: "en tests"
      env: TEST_SCRIPT="en_tests.py"
    - name: "la tests"
      env: TEST_SCRIPT="la_tests.py"
    - name: "pst from tests"
      env: TEST_SCRIPT="pst_from_tests.py"
    - name: "da tests"
      env: TEST_SCRIPT="da_tests.py"
    - name: "moouu tests"
      env: TEST_SCRIPT="moouu_tests.py"
    - name: "full meal deal tests"
      env: TEST_SCRIPT="full_meal_deal_tests.py"
    - name: "plot tests"
      env: TEST_SCRIPT="plot_tests.py"
    - name: "pst tests 2"
      env: TEST_SCRIPT="pst_tests_2.py"
    - name: "notebook tests"
      env: TEST_SCRIPT="autotest_notebooks.py"



addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - g++-6
      - python-pip
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
      - gdal-bin
      - libgdal-dev
      - liblapack-dev
env:
  global:
    - NO_NET=1
before_install:
  - if [[ ! -d "$HOME/.local/bin" ]]; then
      mkdir "$HOME/.local/bin";
    fi
  - export PATH="$HOME/.local/bin:$PATH"
  - ln -fs /usr/bin/gfortran-6 "$HOME/.local/bin/gfortran" && gfortran --version
  - ls -l /usr/bin/gfortran-6
  - ln -fs /usr/bin/gcc-6 "$HOME/.local/bin/gcc" && gcc --version
  - ls -l /usr/bin/gcc-6
  - ln -fs /usr/bin/g++-6 "$HOME/.local/bin/g++" && g++ --version
  - ls -l /usr/bin/g++-6
  - export CXX="g++"
  - git clone -b develop --depth 1 https://github.com/usgs/pestpp
  - cd pestpp/src
  - bindir=../../../../bin/linux COMPILER=gcc CXX=g++ FC=gfortran STATIC=no make -j 20 install
  - cd ../../
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PATH="$HOME/pestpp/bin/linux:$PATH"
  - conda update --yes conda
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas nose matplotlib jupyter notebook cartopy sphinx nbconvert
  - pip install coveralls
  - pip install pyshp
  - pip install nose-timer
  - pip install nbsphinx
  - #pip install git+https://github.com/modflowpy/flopy.git@develop
  - git clone -b develop --depth 1 https://github.com/modflowpy/flopy.git
  - cd flopy
  - python setup.py install
  - cd ..
  - pip install https://github.com/modflowpy/pymake/zipball/master
  - python setup.py install
script:
  - export PYTHONPATH=$PYTHONPATH:.
  - nosetests -v --with-id --nocapture --with-timer -w ./autotest --with-coverage --cover-package=pyemu $TEST_SCRIPT

after_success:
  - cd docs
  - make html
  - cd ..
#   - coveralls


