
image: Visual Studio 2017
platform: x64
environment:
  
  matrix:
    - PYTHON_VERSION: "3.7"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"

build: false

cache:
  - '%LOCALAPPDATA%\pip\Cache'
  - '%USERPROFILE%\.cache\pyemu'

init:
  - echo %PYTHON_VERSION% %CONDA_INSTALL_LOCN%

install:
  - git clone -b develop --depth 1 https://github.com/usgs/pestpp
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd pestpp
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
  - ninja -j2
  - cd ..
  - cd ..
  - copy /Y pestpp\bin\*.* bin\win\
  - set PATH=%CONDA_INSTALL_LOCN%;%CONDA_INSTALL_LOCN%\scripts;%PATH%;
  - set PYTHONUNBUFFERED=1
  # for msinttypes and newer stuff
  - conda config --set always_yes true
  - conda update conda
  - conda update --all
  - conda config --set show_channel_urls yes
  - conda config --prepend channels conda-forge
  - conda info -a

  - conda install --yes python=%PYTHON_VERSION% pip numpy scipy pandas nose matplotlib jupyter notebook cartopy
  - pip install coveralls
  - pip install pyshp
  - pip install nose-timer
  - pip install git+https://github.com/modflowpy/flopy.git@develop
  - pip install https://github.com/modflowpy/pymake/zipball/master
  # Show the installed packages + versions
  - conda list

test_script:
  - python setup.py install
  - nosetests -v --with-id --nocapture --with-timer -w autotest full_meal_deal_tests.py:freyberg_test
  - nosetests -v --with-id --nocapture --with-timer -w autotest utils_tests.py

after_test:
 - echo "done"
matrix:
  fast_finish: true